- adi_update_tools.sh
Motor control utils are not available anymore on the mathworks_tools
repository. They were removed by: https://github.com/analogdevicesinc/MathWorks_tools/commit/6b679dc3b896c9b74d1a8334064e05ea6c36c4f8
Signed-off-by: Bogdan Togorean <bogdan.togorean@analog.com>
> adi_update_tools: Remove mathworks_tools from BUILDS_DEV

- adi_update_tools.sh
python3-scipy and sox are required by audio loopback test
script on rfsom-box so add them to install
Also split install list on multiple lines
Signed-off-by: Bogdan Togorean <bogdan.togorean@analog.com>
> adi_update_tools.sh: Add python-scipy and sox

- adrv9009_multichip_sync.sh
Similar to MCS button in the ADRV9009 IIO Oscilloscope plugin.
Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>
> adrv9009_multichip_sync.sh: Helper script for MCS on ADRV9009-ZU11EG

- iiod_usbd.init
For context attributes from file support - libiio needs to be build with -DWITH_LOCAL_CONFIG=ON
In addition it requires libini (https://github.com/pcercuei/libini)
Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>
> iiod_usbd.init: Add SYSTEM ID to libiio Context Attributes

- iiod_usbd.init
On Talise SOM with kernel 4.19, the current logic is pretty racy and won't
always init the USB gadget.
This change bumps the initial timeout to 1 second and does 10 retries in
case the `echo` returns an error.
Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
> iiod_usbd.init: make USB gadget init more robust

- adi_update_tools.sh
if we are using a modern libiio (master) turn on WITH_LOCAL_CONFIG
and ensure we build with Python bindings (which was turned off by default)
recently.
https://github.com/analogdevicesinc/libiio/commit/f1faa2816c076eaea285ac4683fefa1c4f5878c9
Signed-off-by: Robin Getz <robin.getz@analog.com>
> adi_update_tools.sh: libiio; turn on python bindings and local config

- adi_update_tools.sh
This patch will use the cmake build option for iio-oscilloscope. It will
fix the issue with deprecated gksudo desktop entry. This has been replaced
with pkexec but only for the cmake build option not for the old make.
Also moving forward cmake will be the default for this tool so it makes
more sense to shift now.
Signed-off-by: Mircea Caprioru <mircea.caprioru@analog.com>
Tested on Raspberry Pi
> adi_update_tools: Shift iio-oscilloscope to cmake build

- adi_update_tools.sh
In older versions of libiio, we used a static avahi service file,
now that we added better support inside iiod, we no longer need this.
It's not included in the libiio installer anymore.
Signed-off-by: Robin Getz <robin.getz@analog.com>
> remove the no longer needed iio.service file

- adi_update_tools.sh
This modication will check for what init system is running on the target and
add cmake extra flags to the configuration.
systemd: -DWITH_SYSTEMD
sysvinit: -DWITH_SYSVINIT
upstart: -DWITH_UPSTART
Signed-off-by: Mircea Caprioru <mircea.caprioru@analog.com>
> adi_update_tools: Check for init system

- adi_update_tools.sh
Add CMAKE_INSTALL_PREFIX for iio-oscilloscope.
Signed-off-by: Mircea Caprioru <mircea.caprioru@analog.com>
> adi_update_tools: Add install prefix for iio-oscilloscope

- adi_update_tools.sh
Add BRANCH option when a repository is cloned for the first time. Before
this change the builds ran from master branch.
Signed-off-by: Mircea Caprioru <mircea.caprioru@analog.com>
> adi_update_tools: Add BRANCH when checking out for the first time

- usb_otg.sh
This script can be used to enable/disable/check status of USB OtG in the device tree of supported hardware platforms.
Currently, only the Zedboard is supported.
Signed-off-by: Michael Bradley <michael.bradley@analog.com>
> Add script for controlling USB OtG setting in devicetree

- test_adrv9002_fh.sh
This is a test script for testing fast frequency hopping in ADRV9002
designs. It depends on libiio (and tools) and realpath (which is
installed by default in almost every distribution).
The script provides some configurability but also enforces some defaults:
* HOP signal 1 will control RX1/TX1.
* HOP signal 2 will control RX2/TX2.
* If HOP1 is given we default to mode: LO_RETUNE_REALTIME_PROCESS
* If HOP2 is given we default to mode: LO_RETUNE_REALTIME_PROCESS_DUAL_HOP
* As a consequence of the above item, the max table size is 32.
* DGPIO_2 will be used to control the hop signal.
* DGPIO_3 is the base for the gpio's used when the index table control
is set to gpio.
* The script only tests one port on each call and the port to test is
deduced from the hop signal and --rx flag parameter …
> scripts: add script for testing ADRV9002 frequency hopping

- usb-gadget-service/systemd/iiod_ffs.service
IIOD does not handle the hardware changing (in /dev or /sys) after it
has been started. Therefore, we must ensure that all modules have been
loaded before IIOD starts.
Note that this is explicitely marked as a bad practice in systemd docs,
which recommends the service to handle udev events instead. Since IIOD
and libiio don't support hardware hotplug we don't really have a choice
right now, but this workaround should be dropped as soon as hotplug
support has been added.
Signed-off-by: Paul Cercueil <paul@crapouillou.net>
> usb-gadget-service: Add dependency on systemd-udev-settle.service

- usb-gadget-service/schemes/iio_acmx2_rndis.scheme
This adds the scheme that provide IIO, 2xACM, and RNDIS that
supports the ADI evaluation platform.
Signed-off-by: Michael Bradley <Michael.Bradley@analog.com>
> usb-gadget-service: Add scheme for eval platform

- adi_update_tools.sh
Remove installation of fmcomms1-eeprom-cal component
since we do not support fmcomms1 anymore.
Signed-off-by: stefan.raus <stefan.raus@analog.com>
> adi_update_tools.sh: Remove fmcomms1-eeprom-cal

- test_adrv9002_fh.sh
The sleep was being done in the end of each iteration. However, it
should be done between starting the frame and stopping it, otherwise it
might become imperceptible to watch the frame on, for example, a
spectrum analyzer.
Signed-off-by: Nuno Sá <nuno.sa@analog.com>
> test_adrv9002_fh: set sleep in the right place

- usb-gadget-service/install_gt.sh
This installs the iio_acmx2_rndis.scheme.
Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>
> usb-gadget-service/install_gt.sh: Install missing iio_acmx2_rndis.scheme

- enable_dummy_display.sh
The VNC serever is not working on boards without any video ports.
This scripts adds a 720p dummy display that will be available for the
VNC server.
Also, this change fixes the lightDM timeout when rebooting the boards
without video ports.
Signed-off-by: Sergiu Cuciurean <sergiu.cuciurean@analog.com>
> dummy_display: Add dummy display script

- adi_update_boot.sh
If boot partition descriptor file ('latest_boot.txt')
contains windows carriage/return, replace it with unix
characters. Otherwise, when the file is parsed, there
will appear "%0D" chars at the end of every line.
Signed-off-by: stefan.raus <stefan.raus@analog.com>
> adi_update_boot.sh: Replace windows carrige/return

- adi_update_tools.sh
Link the libad9166-iio repository to the required tools for the linux
ADI image.
Signed-off-by: Antoniu Miclaus <antoniu.miclaus@analog.com>
> adi_update_tools.sh: add libad9166-iio

- adi_update_tools.sh
'iio_jesd204_fsm_sync' was build only if adi_update_tools.sh
was run with DEV parameter. Add it in 2021_R1 and next releases.
Delete cases for obsolete repositories.
Signed-off-by: stefan.raus <stefan.raus@analog.com>
> adi_update_tools.sh: add wiki_scripts on release

- adi_update_tools.sh
By default enable the option to install python bindings for the
libad9166-iio required for the pyadi-iio cn0511 support.
Signed-off-by: Antoniu Miclaus <antoniu.miclaus@analog.com>
> adi_update_tools: install bindings for libad9166

- Makefile
- lightdm_timeout.conf
lightdm gets stuck in a loop trying to start X11 on a board with no screen attached. Add a TimeoutStopSec of 5 seconds to prevent prolonging shutdown sequence for too long.
Signed-off-by: Cosmin Tanislav <demonsingur@gmail.com>
> Override lightdm timeout

- adi_update_tools.sh
Create /ADI_git_repos_info.txt file in which are saved all information (git repository link, branch and git commit) of all ADI repos that are cloned/updated and built.
Signed-off-by: stefan.raus <stefan.raus@analog.com>
> adi_update_tools.sh: save ADI repos git info

- adi_update_tools.sh
Add case insensivity for release parameter and delete the case that didn't made sense - input parameter was non-null but also didn't matched any defined value, so created link to git repo was a unexisting one.
> adi_update_tools: add case insensivity on param

- adi_update_tools.sh
Change shell from sh to bash, otherwise '[[' and ']]' won't be recognized and the script will give '[[: not found', the switch condition over input parameter won't work properly , going alway on using 'master' branches.
> adi_update_tools.sh: fix script

- usb-gadget-service/scripts/iiod_context.sh
When there are colors codes in the axi sysid strings, the resulting /etc/libiio.ini is wrongly written. Well, this only happens in the second time the file is written. If there's no file, it works for the fist time.
Anyways, this all means that we are unable to get the libiio context from a remote connection.
In commit 06afede486c3 ("iiod_context.sh: remove non-printable chars in dmesg"), we tried to remove the specific color codes from the string but that change is missing to properly escape '\' so that sed actually matches the pattern to remove. Let's fix that...
> iiod_context: fix hdl sysid with colors

- test_adrv9002_fh.sh
Fix the test running on zynqmp. Also get rid of a bash warning.
> adrv9002 fh test

- adi_update_boot.sh
- adi_update_tools.sh
Multiple commits for:
- change default branches to main for the repos that already have 'main'
- set "linux_image_ADI-scripts" default to 'main' ('master' won't be deleted yet since old versions of the adi_update_tools.sh script are using it - so whenever 'adi_update_tools.sh' is called from old SD card images)
- **add case for 2022_r2 release**
- remove very old releases (2018_r1/2 and 2019_r1//2)
- fix some branches to be used for 2021_r2 (at this moment they are in sync with main / master, but for cases when there wll be compatibility-breaker commits into main / master)
> Update to main branches

- adi_update_boot.sh
There is a file called 'overlay_map.dtb' in /boot/overlays. If it's deleted, whenever we use line 'dtoverlay=vc4-kms-v3d' in config.txt, the bootloader will load 'vc4-kms-v3d' exactly as it is. But if overlay_map.dtb exists, and booting on RPI4, it will actually use 'vc4-kms-v3d-pi4'.
There are 2 solutions to fix the problem (no video output after adi_update_boot.sh is run):
1. Keep overlay_map.dtb and 'dtoverlay=vc4-kms-v3d' in config.txt
2. No overlay_map.dtb and, after loading 'dtoverlay=vc4-kms-v3d' (that works for RPI 2 and 3, load the pi4 specific one if booting on RPI4, like:
```
[pi4]
dtoverlay=vc4-kms-v3d-pi4
```
This PR implements the  first one.
> adi_update_boot.sh: keep overlays/overlay_map.dtb

- enable_dhcp.sh
- enable_static_ip.sh
Starting with Debian 12, network manager service changed it's name to 'NetworkManager'. 
enable_dhcp.sh: change 'network-manager' to 'NetworkManager' 
enable_static_ip.sh: change 'network-manager' to 'NetworkManager'
> Update network manager service

- Makefile
'make' command is run at built time, so there is no need to reload systemd manager configuration. 
'systemctl daemon-reload' is only needed at boot time to reload services without rebooting.
> Makefile: remove daemon-reload

- adi_update_tools.sh
The main branch of colorimeter was updated to work with a newer version of Python(>3.11) in analogdevicesinc/colorimeter#7. Update `adi_update_tools.sh` to use 2023_R2 branch of colorimeter.
> adi_update_tools.sh: Fix colorimeter dependency

- enable_dhcp.sh
- enable_static_ip.sh
Replace legacy command 'service' with 'systemctl'. The second one is more suitable for systemd-based systems (modern Linux distributions).
Restart the networking service after running these scripts. The networking service is responsible for reloading information from the '/etc/network/interfaces' file, which is overwritten by both scripts.
> Update network scripts

- Makefile
- fix-display-port.service
- fix_DP_audio.sh
- fix_x11.sh
- jupiter_scripts/fan-control
- jupiter_scripts/fan-control.service
- jupiter_scripts/fix-display-port.service
There are 2 new files for Jupiter:
- 'fan-control.service' 
- 'fan-control' (sh script)
I have added them in /jupiter_scripts and copied on desired paths during 'make install'.
There is a condition to start the service only if there is detected "Jupiter SDR"  ( from "/sys/firmware/devicetree/base/model"). 
The second big change is on fix_x11.sh:
- extended condition to cover Jupiter case
- delete file created by enable_dummy_display, if exists
The third big change is the fix for DP audio codec
- fix DP audio sampling rate (to get rid of dmesg errors)
- have an oneshot service that fix DP (audio and video)
> Add Jupiter SDR specific scripts

- jupiter_scripts/fix-display-port.service
Remove this service after copying it to the main directory since it is not a jupiter specific service.
> Remove fix service from jupiter directory

- fix_DP_audio.sh
Suppress sed exit code and errors so that the script will run with success even if the file does not exist.
> fix_DP_audio: suppress sed exit code

- usb_otg.sh
The script was trying to read the node 'axi' from /boot/devicetree.dtb but this file does not exist. Replace it with /boot/system.dtb
Fix also value of 'USB' variable conform with nodes from zynqmp.dtsi.
> usb_otg.sh: fix for zynqmp

- fix_DP_audio.sh
- fix_x11.sh
In 'if' statement, 'grep' always returned exit code to enter the first branch, no matter the contents of the checked file. Fixed that by removing the evaluation of the conditional expressions ( '[]' ).
> fix_x11, fix_DP_audio: fix 'if' statement

- fix-display-port.service
- fix_DP_audio.sh
- fix_x11.sh
In 'if' statement, 'grep' always returned exit code to enter the first branch, no matter the contents of the checked file. Fixed that by removing the evaluation of the conditional expressions ( '[]' ).
Fix error "zynqmp_dp_snd_codec0: Failed to get required clock freq" by setting default sample rate to 48000.
Create fix-display-port.service that runs fix_x11.sh and fix_DP_audio.sh at boot.
> Fix 'if' statement in 'fix_x11.sh' and add a fix for DP audio codec

- fix_x11.sh
Create /etc/X11/xorg.conf file if there is detected a platform with Display Port and remove it if there is detected a non-DP one.
The previous implementation doesn't make sense, since will try to delete the file that couldn't be created.
> fix_x11: remove xorg.conf only for non-DP platforms

- adi_update_boot.sh
- adi_update_tools.sh
Add 2023_r2 branches also in master, in order to have them also in older images.
Default branch was switched to 'main' during 2022_r2 release, so this change will allow people that use older images (where default is 'master') to update tools and boot files to 2023_r2.
Signed-off-by: Stefan Raus <Stefan.Raus@analog.com>
(cherry picked from commit 8e0e97781da02c1d79b47cde40788b5d7de0b38b)
> adi_update_boot/tools: add 2023_r2 branches

- adi_update_boot.sh
- adi_update_tools.sh
The scripts "adi_update_boot.sh" and "adi_update_tools.sh" got tested with parameter '2023_r2' and they work fine.
Set default parameter value to "2023_r2".
> adi_update_boot/tools:set default param to 2023_r2

- test_adrv9002_fh.sh
With the latest support in [adrv9002](https://github.com/analogdevicesinc/linux/pull/2582), we can now control the enable pins directly in the driver and that could break this script in case the devicetree sets thos GPIOs (which we want to do by default). Hence, fix it by assuming that we can control ensm_mode in case we can't export the GPIO.
On top it, we're also adding support for the Jupiter SDR.
> adrv9002 frequency hopping test script
